LondonBlog/Models/Comments/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.Models.Comments
{
    public class Comment
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public DateTime Created { get; set; }
    }
}

LondonBlog/Models/Comments/MainComment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.Models.Comments
{
    public class MainComment :Comment
    {
        public List<SubComment> SubComments { get; set; }
    }
}

LondonBlog/Models/Comments/SubComment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.Models.Comments
{
    public class SubComment :Comment
    {
       public int MainCommentId { get; set; } 
    }
}

LondonBlog/Models/ErrorViewModel.cs
using System;

namespace LondonBlog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LondonBlog/Models/Post.cs
using LondonBlog.Models.Comments;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Title { get; set; } = "";
        public string Body { get; set; } = "";
        public string Image { get; set; } = "";
        public DateTime Created { get; set; } = DateTime.Now;

        public List<MainComment> MainComments { get; set; }
    }
}

LondonBlog/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.ViewModels
{
    public class CommentViewModel
    {
        [Required]
        public int PostId { get; set; }
        [Required]
        public int MainCommentId { get; set; }
        [Required]
        public string Message{ get; set; }
    }
}

LondonBlog/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.ViewModels
{
    public class LoginViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

LondonBlog/ViewModels/PostViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace LondonBlog.ViewModels
{
    public class PostViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; } = "";
        public string Body { get; set; } = "";
        public IFormFile Image { get; set; } = null;
        public int MainCommentId { get; set; }
    }
}

LondonBlog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LondonBlog.Models;
using LondonBlog.Data;
using LondonBlog.Data.Repository;
using LondonBlog.Data.FileManager;
using LondonBlog.Models.Comments;
using LondonBlog.ViewModels;

namespace LondonBlog.Controllers
{
    public class HomeController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public HomeController(
            IRepository repo,
            IFileManager fileManager
            
            )
        {
            _repo = repo;
            _fileManager = fileManager;

          

        }
        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }

       
        public IActionResult Post(int id)
        {
            var post = _repo.GetPost(id);
            return View(post);
        }
        [HttpGet("/Image/{image}")]
        public IActionResult Image(string image)
        {
            var mime = image.Substring(image.LastIndexOf('.')+1);
            return new FileStreamResult(_fileManager.ImageStream(image),$"image /{ mime }");
        }

    public async Task<IActionResult> Comment(CommentViewModel vm)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Post",new {id =vm.PostId });

            var post = _repo.GetPost(vm.PostId);
            if (vm.MainCommentId == 0)
            {
                post.MainComments = post.MainComments ?? new List<MainComment>();

                post.MainComments.Add(new MainComment
                {
                    Message = vm.Message,
                    Created= DateTime.Now,

                });
                _repo.UpdatePost(post);
            }
            else
            {
                var comment = new SubComment
                {
                    MainCommentId = vm.MainCommentId,
                    Message =vm.Message,
                    Created=DateTime.Now,
                };
            }
            await _repo.SaveChangesAsync();

               return RedirectToAction("Post", new { id = vm.PostId });

        }
    }
}

LondonBlog/Controllers/PanelController.cs
using LondonBlog.Data.FileManager;
using LondonBlog.Data.Repository;
using LondonBlog.Models;
using LondonBlog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LondonBlog.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
        private IRepository _repo;
        private IFileManager _fileManager;

        public PanelController(
            IRepository repo,
             IFileManager fileManager
            )
        {
            _repo = repo;
            _fileManager = fileManager;
        }
        public IActionResult Index()
        {
            var posts = _repo.GetAllPosts();
            return View(posts);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
                return View(new PostViewModel());
            else
            {
                var post = _repo.GetPost((int)id);
                return View(new PostViewModel
                {
                    Id = post.Id,
                    Title=post.Title,
                    Body=post.Body


                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Image =await _fileManager.SaveImage(vm.Image)
                //handle image
            };

            if (post.Id > 0)
                _repo.UpdatePost(post);
            else
                _repo.AddPost(post);

            if (await _repo.SaveChangesAsync())
                return RedirectToAction("Index");
            else
                return View(post);
        }
        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _repo.RemovePost(id);
            await _repo.SaveChangesAsync();
            return RedirectToAction("Index");
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
      


    }
    
}

LondonBlog/Views/Home/Index.cshtml
@model IEnumerable<Post>

@{
    ViewData["Title"] = "Home Page";

}


<div>
  @*  <ul>
        @foreach (var post in Model)
        {
            <li>
                <a asp-controller="Home" asp-action="Post" asp-route-id="@post.Id">
                    @post.Title
                </a>
                -

            </li>
        }

    </ul>*@
</div>
<html>
<style>
    h1, h2, h3, h4, h5, h6 {
        font-family: "Oswald"
    }

    body {
        font-family: "Open Sans"
    }
</style>
<body class="w3-light-grey">
    <div class="w3-content" style="max-width:1600px">

        <!-- Header -->
        <header class="w3-container w3-center w3-padding-16 w3-white ">
            <h1 class="w3-xxxlarge"><b>Food Recipes Blog</b></h1>
            <h6>Welcome to the blog of <span class="w3-tag">Best Food Recipes </span></h6>
        </header>

        <!-- Image header -->
        <header class="w3-display-container w3-wide" id="home">
            <img class="w3-image" src="~/content/static/bookk.jpeg" alt="food Blog" width="1600" height="800">
            <div class="w3-display-left w3-padding-large">
                <h1 class="w3-text-white">Food</h1>
                <h1 class="w3-jumbo w3-text-white w3-hide-small"><b> Recipes  BLOG</b></h1>
                <h6><button class="w3-button w3-white w3-padding-large w3-large w3-opacity w3-hover-opacity-off" onclick="document.getElementById('subscribe').style.display='block'">SUBSCRIBE</button></h6>
            </div>
        </header>
        <!-- Grid -->
        <div class="w3-row w3-padding ">
            @foreach (var post in Model)
            {

                var image_path = $"/Image/{post.Image}";
                <!-- Blog entries -->
                <div class="w3-center">


                    <!-- Blog entry -->
                    <div class="w3-container w3-white w3-margin w3-padding-large">

                        <div class="w3-center">

                            <h3>
                                <a asp-controller="Home" asp-action="Post" asp-route-id="@post.Id">
                                    @post.Title
                                </a>
                            </h3>




                            <h5> <span class="w3-opacity">@post.Created</span></h5>
                        </div>

                        <div class="w3-justify">
                            <img src="@image_path" style="width:70%" class="w3-padding-16 ">
                            <p>
                              
                             
                            </p>

                            <p class="w3-left"><button class="w3-button w3-white w3-border" onclick="likeFunction(this)"><b><i class="fa fa-thumbs-up"></i> Like</b></button></p>
                           
                              
                            </div>
                        </div>
                    </div>

                    <hr>


                

            }


            <!-- Subscribe Modal -->
            <div id="subscribe" class="w3-modal w3-animate-opacity">
                <div class="w3-modal-content" style="padding:32px">
                    <div class="w3-container w3-white">
                        <i onclick="document.getElementById('subscribe').style.display='none'" class="fa fa-remove w3-transparent w3-button w3-xlarge w3-right"></i>
                        <h2 class="w3-wide">SUBSCRIBE</h2>
                        <p>Join my mailing list to receive updates on the latest blog posts and other things.</p>
                        <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
                        <button type="button" class="w3-button w3-block w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('subscribe').style.display='none'">Subscribe</button>
                    </div>
                </div>
            </div>


            <script>
                // Toggle between hiding and showing blog replies/comments
                document.getElementById("myBtn").click();
                function myFunction(id) {
                    var x = document.getElementById(id);
                    if (x.className.indexOf("w3-show") == -1) {
                        x.className += " w3-show";
                    } else {
                        x.className = x.className.replace(" w3-show", "");
                    }
                }

                function likeFunction(x) {
                    x.style.fontWeight = "bold";
                    x.innerHTML = "✓ Liked";
                }
            </script>

</body>
</html>

LondonBlog/Views/Home/Post.cshtml
@model  Post

@{
    ViewData["Title"] = "Home Page";
}

    <div class="container">
        <div class="post no-shadow">
            <h2>@Model.Title</h2>
            <hr />
            @if (!String.IsNullOrEmpty(Model.Image))
            {
                var image_path = $"/Image/{Model.Image}";
                <img src="@image_path" style="width:70%" class="w3-padding-8  ">
            }
            <hr />
        </div>
        <p>@Model.Body</p>


 


<h3>Make a Comment</h3>
        <div class="comment-section">
            @{
                await Html.RenderPartialAsync("_MainComment", new CommentViewModel { PostId = Model.Id, MainCommentId = 0 });
            }

          


        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.MainComments)
                    </th>
                    <th>
                     
                    </th>
                 
                </tr>
            </thead>
            <tbody>
                @foreach (var c in Model.MainComments)
                {
                    <tr>
                        <td>
                            @c.Message
                        </td>

                        <td>
                            @c.Created
                        </td>

                    </tr>
                }
            </tbody>
        </table>
        <body style="background-color:blanchedalmond">
        </body>
    </div>
       

LondonBlog/Views/Home/_MainComment.cshtml
@model  CommentViewModel

@{ 

}

<div>

    <form method="post" asp-controller="Home" asp-action="Comment">

        <input asp-for="PostId" type="hidden" />
        <input asp-for="MainCommentId" type="hidden" />
        <input asp-for="Message" />
        <button type="submit">Submit</button>
    </form>
</div>

LondonBlog/Views/Panel/Edit.cshtml
@model PostViewModel

@{

}


<div class="row">
    <div class="col-md-4">
        <form asp-controller="Panel" asp-action="Edit" method="Post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
               <h4> <label asp-for="Title" class="control-label"></label></h4>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
               <h4> <label asp-for="Body" class="control-label"></label></h4>
                <input asp-for="Body" class="form-control" />
                <span asp-validation-for="Body" class="text-danger"></span>
            </div>
            <div class="form-group">
               <h4> <label asp-for="Image" class="control-label"></label></h4>
                <input asp-for="Image" class="form-control-file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
   <h5> <a asp-action="Index">Back to List</a></h5>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<body style="background-color:powderblue;"></body>

LondonBlog/Views/Panel/Index.cshtml
@model IEnumerable<Post>

@{
    ViewData["Title"] = "Home Page";
}
<br />

<h2><i>Admin panel</i></h2>
<br />
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var post in Model)
        {
            <tr>
                <td>
                    @post.Title
                </td>
             
                <td>
                  @post.Image
                </td>
                <td>
                    -
                    <a asp-controller="Panel" asp-action="Edit" asp-route-id="@post.Id">
                        Edit
                    </a>
                    -
                    <a asp-controller="Panel" asp-action="Remove" asp-route-id="@post.Id">
                        Remove
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<body style="background-color:whitesmoke">
</body>

LondonBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodBlog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    

</head>

<body >
    <header>
        <div class="w3-bar w3-black w3-hide-small">
            <a class="w3-bar-item w3-button navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Best Recipes BLOG </a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-facebook-official"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-instagram"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-snapchat"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-flickr"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-twitter"></i></a>
            <a href="#" class="w3-bar-item w3-button"><i class="fa fa-linkedin"></i></a>
            <a href="#" class="w3-bar-item w3-button w3-right"><i class="fa fa-search"></i></a>

        </div>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">

            <div class="container">

              
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Panel" asp-action="Edit">Creat Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Panel" asp-action="Index">Admin panel</a>
                      

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted ">

        <a href="#" class="w3-button w3-black w3-padding-large w3-margin-bottom"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
        <div class=" w3-margin">
            <div class="w3-container ">
                <h4>Follow Me</h4>
            </div>
          
                <div class="w3-container w3-xlarge w3-padding">
                    <i class="fa fa-facebook-official w3-hover-opacity"></i>
                    <i class="fa fa-instagram w3-hover-opacity"></i>
                    <i class="fa fa-snapchat w3-hover-opacity"></i>
                    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
                    <i class="fa fa-twitter w3-hover-opacity"></i>
                    <i class="fa fa-linkedin w3-hover-opacity"></i>
                </div>
            </div>
       
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>